/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * Taller sobre paso por valor y paso por referencia
 *
 ******************************************************************************
 */

#include <stdint.h>

// Paso por valor básico
void duplicarNumero (uint8_t numero){
	numero *= 2;

}

// Paso por referencia
void duplicarNumeroRef (uint8_t *numero){
	*numero = (*numero) * 2;
}

// Paso por valor reasignando valor
uint8_t duplicarNumeroReturn(uint8_t numero){
	return (numero * 2);
}

// Arreglos por referencia
void abonarDeudas (uint16_t misDeudas[], uint8_t cantidadDeudas){

	// For para recorrer el arreglo
	for (uint8_t i = 0; i < cantidadDeudas; i++){
		misDeudas[i] /= 2;
	}
}

void stringCaseConverter (uint8_t *string){
	// Desconocemos la longitud del caracter

	// Contador
	uint8_t i = 0;

	//
	while (string[i] != '\0'){

//		// Si es mayúscula
//		if (string[i] > 64 && string[i] < 91){
//			string[i] = string[i] + 32;
//		}
//		// Si es minúscula
//		else if (string[i] > 96 && string[i] < 122){
//			string[i] = string[i] - 32;
//		}

		if ((*(string + i) > 64) && (*(string + i) < 91)){
			*(string + i) = *(string + i) + 32;
		}

		else if ((*(string + i) > 96) && (*(string + i) < 123)){
			*(string + i) = *(string + i) - 32;
		}

		else{
			*(string + i) = *(string + i);
		}
	}
}

int main(void)
{
    uint8_t n = 10;

    // Pasamos por valor
    duplicarNumero(n);

    uint8_t m = 20;

    // Pasamos por referencia
    duplicarNumeroRef(&m);

    // Reasignamos valores
    n = 12;
    m = 14;

    n = duplicarNumeroReturn(n);

    n = 50;

    // Ejemplo String Básico

    uint8_t miPrimerString[] = "H0llllAh M8undo";

    n = 0;

    // Ya de por sí es un puntero
    uint16_t deudasMensuales[5] = {15000,2500,200,3600,2};

    abonarDeudas(deudasMensuales, 5);

    // Crear función llamada stringCaseConverter que no retorne ningún valor
    // y reciba un string, la función cambia las letras mayúsculas por minúsculas
    stringCaseConverter(miPrimerString);



}



